In [40]:
import pandas as pd
import numpy as np

ROWS = 15

def handle(event, context, **kwargs):
    # return a pandas dataframe directly, handler will return as json
    df = pd.DataFrame({
        "0Seq": list(range(0, ROWS)),
        "1Rand": np.random.randint(0, 100, ROWS),
        "2Nan": np.nan,
        "3None": None,
        "4Inf": np.inf
        })
    return df

In [52]:
handle(None, None)

    Seq  Rand  Nan  None  Infinity
0     0     4  NaN  None       inf
1     1    15  NaN  None       inf
2     2    28  NaN  None       inf
3     3    94  NaN  None       inf
4     4    67  NaN  None       inf
5     5    84  NaN  None       inf
6     6    28  NaN  None       inf
7     7     5  NaN  None       inf
8     8    34  NaN  None       inf
9     9    42  NaN  None       inf
10   10    38  NaN  None       inf
11   11    23  NaN  None       inf
12   12    52  NaN  None       inf
13   13    26  NaN  None       inf
14   14    15  NaN  None       inf